name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Give execute permission to Maven Wrapper
        run: chmod +x ./starwarsbackend/mvnw

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "21"

      - name: Build and test backend
        working-directory: ./starwarsbackend
        run: |
          ./mvnw clean install
          ./mvnw test

  frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./starwars-frontend
        run: npm install

      - name: Run frontend tests
        working-directory: ./starwars-frontend
        run: npm test -- --watch=false --browsers=ChromeHeadless
